language: cpp
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y software-properties-common
 - sudo apt-get install -y kpartx qemu-arm-static debootstrap lvm dosfsck

script: "sudo ./bootstrap.sh example-rpi-2-b-ubuntu-trusty-minimal"

